truncate table sh_admin_authority;
truncate table sh_admin_authority_group;

ALTER TABLE `sh_duobaohui`.`sh_admin_authority`
ADD UNIQUE INDEX `uidx_admin_authority` (`url` ASC);

INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/add-activity','活动添加录入');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/create-period',NULL);
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/goods-by-category',NULL);
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/list-pre','活动管理－活动列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/period-list','活动期信息');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/save-activity','活动添加结果');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/update-auto',NULL);
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/update-online',NULL);
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/activity/update-pre','修改活动录入页面');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/add-authority','添加权限节点');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/add-authority-user','添加管理员');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/authority-group-list','管理组列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/authority-list','权限节点列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/authority-user-list','管理员列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/delete-authority','删除节点');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/edit-authority','编辑权限节点');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/save-authority','保存添加的权限节点');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/save-authority-user','添加管理员表单');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/authority/save-edit-authority','保存编辑权限节点');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/banner','banner列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/banner/add','banner添加');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/banner/del','banner删除');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/banner/edit','banner编辑');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/banner/index','商品banner');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill','账务明细');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill/alipay-account','支付宝账务明细异常');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill/change-status','处理虚假订单信息');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill/edit-alipay','修复真实重复订单状态');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill/index','出入账管理-统计');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill/pay-list','出入账管理-支付记录');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/bill/search','根据活动期数或用户查询账务异常');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/client/release-new-version','发布客户端新版本');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/client/release-new-version-pre','发布客户端新版本');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/client/version-list','客户端版本管理');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/client/version-list-json','客户端版本权限列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/add-goods','添加商品goods');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/delete-goods','删除商品');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/edit-goods','修改商品');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/list','商品列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/save-goods','保存添加商品的数据');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/umeditor-img','umeditor编辑器上传图片');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/update-goods','保存更新商品数据');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/goods/upload-img-to-local','上传图片');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/index','首页');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/order/order-detail','订单管理－订单详情');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/order/order-list','订单管理－订单列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/order/order-modify','订单管理－修改订单状态');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/add-shaidan','添加晒单');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/delete-shaidan','删除晒单');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/edit-shaidan','编辑晒单');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/js-qiniu-token','获取七牛上传图片的token');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/list','晒单列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/save-shaidan','保存添加晒单的数据');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/shaidan-list-by-wangyi','晒单网易数据');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/update-shaidan','更新晒单数据');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shaidan/win-user-list','获取虚拟用户中奖列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shop/add-one-shop','添加商户');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shop/add-shop','添加商户');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shop/del','删除商户');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shop/edit','编辑商户信息');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shop/edit-shop','编辑商户信息');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/shop/shop-list','商户列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/user/logout','后台管理-退出');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/user/send-verify-code','后台登录发送验证码');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('/admin/user/user-list','用户列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('admin/activity/list-pre','活动管理列表');
INSERT INTO `sh_admin_authority` (`url`,`url_notes`) VALUES ('admin/user/user-list','用户列表');

INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,1);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,2);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,3);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,4);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,5);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,6);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,7);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,8);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,9);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,10);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,11);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,12);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,13);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,14);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,15);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,16);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,17);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,18);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,19);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,20);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,21);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,22);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,23);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,24);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,25);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,26);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,27);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,28);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,29);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,30);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,31);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,32);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,33);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,34);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,35);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,36);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,37);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,38);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,39);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,40);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,41);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,42);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,43);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,44);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,45);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,46);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,47);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,48);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,49);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,50);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,51);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,52);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,53);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,54);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,55);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,56);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,57);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,58);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,59);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,60);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,61);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,62);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,63);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,64);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,65);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,66);
INSERT INTO sh_admin_authority_group(group_id,authority_id) values(1,67);
